log4r_config:
  loggers:
  - name      : production
    level     : WARN
    trace     : 'false'
    outputters :
    - rolling_production
  - name      : development
    level     : DEBUG
    trace     : 'true'
    outputters :
    - rolling_development
  - name      : test
    level     : DEBUG
    trace     : 'true'
    outputters :
    - rolling_test
  outputters:
  - type: RollingFileOutputter
    name: rolling_production
    filename: "log/production.log"
    maxsize: 10000000
    count: 20
    maxtime: 86400
    formatter:
      date_pattern: '%Y-%m-%d %H:%M:%S'
      pattern     : '[%5l %d] %C: %M [%t] %s'
      type        : PatternFormatter
  - type: RollingFileOutputter
    name: rolling_development
    filename: "log/development.log"
    maxsize: 10000000
    count: 20
    maxtime: 86400
    formatter:
      date_pattern: '%Y-%m-%d %H:%M:%S'
      pattern     : '[%5l %d] %C: %M [%t] %s'
      type        : PatternFormatter
  - type: RollingFileOutputter
    name: rolling_test
    filename: "log/test.log"
    maxsize: 10000000
    count: 20
    maxtime: 86400
    formatter:
      date_pattern: '%Y-%m-%d %H:%M:%S'
      pattern     : '[%5l %d] %C: %M [%t] %s'
      type        : PatternFormatter
